biblioteka/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from .forms import LoginForm
from . import views

app_name = 'biblioteka'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^user/login/&', auth_views.login, {'authentication_form': LoginForm}, name='login'),
    url(r'^user/logout/', auth_views.logout, {'next_page': 'biblioteka:index'}, name='logout'),

    url(r'^user/profile/$', views.user_profile, name='userProfile'),

    url(r'^test/$', views.test, name='test'),

    url(r'^book/(?P<pk>[0-9]+)/$',        views.BookDetailView.as_view(), name='bookDetail'),
    url(r'^book/create$',                 views.book_create_view,         name='bookCreate'),
    url(r'^book/(?P<pk>[0-9]+)/update/$', views.book_update_view,         name='bookUpdate'),
    url(r'^book/(?P<pk>[0-9]+)/delete/$', views.BookDeleteView.as_view(), name='bookDelete'),
    url(r'^book/$',                       views.BookListView.as_view(),   name='bookList'),

    url(r'^book/create/isbn/$', views.isbn, name='ISBN'),

    url(r'^book/(?P<book_id>[0-9]+)/mark_read/$',   views.mark_book_read_view,   name='bookMarkRead'),
    url(r'^book/(?P<book_id>[0-9]+)/mark_unread/$', views.mark_book_unread_view, name='bookMarkUnread'),

    url(r'^rental/(?P<book_id>[0-9]+)/create/$',   views.rental_create_view, name='rentalCreate'),
    url(r'^rental/(?P<rental_id>[0-9]+)/return/$', views.rental_return_view, name='rentalReturn'),

    url(r'^author/(?P<pk>[0-9]+)/$',        views.AuthorDetailView.as_view(), name='authorDetail'),
    url(r'^author/$',                       views.AuthorListView.as_view(),   name='authorList'),
    url(r'^author/create$',                 views.author_create_view,         name='authorCreate'),
    url(r'^author/(?P<pk>[0-9]+)/update/$', views.author_update_view,         name='authorUpdate'),
    url(r'^author/(?P<pk>[0-9]+)/delete/$', views.AuthorDeleteView.as_view(), name='authorDelete'),

    url(r'^tag/(?P<pk>[0-9]+)/$',        views.TagDetailView.as_view(), name='tagDetail'),
    url(r'^tag/$',                       views.TagListView.as_view(),   name='tagList'),
    url(r'^tag/create$',                 views.tag_create_view,         name='tagCreate'),
    url(r'^tag/(?P<pk>[0-9]+)/update/$', views.tag_update_view,         name='tagUpdate'),
    url(r'^tag/(?P<pk>[0-9]+)/delete/$', views.TagDeleteView.as_view(), name='tagDelete'),

    url(r'^publisher/(?P<pk>[0-9]+)/$',        views.PublisherDetailView.as_view(), name='publisherDetail'),
    url(r'^publisher/$',                       views.PublisherListView.as_view(),   name='publisherList'),
    url(r'^publisher/create$',                 views.publisher_create_view,         name='publisherCreate'),
    url(r'^publisher/(?P<pk>[0-9]+)/update/$', views.publisher_update_view,         name='publisherUpdate'),
    url(r'^publisher/(?P<pk>[0-9]+)/delete/$', views.PublisherDeleteView.as_view(), name='publisherDelete'),
]

ksiazki/urls.py
from django.conf.urls import include,url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('biblioteka.urls')),
]

biblioteka/models.py
from datetime import datetime

from django.core import validators
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Author(models.Model):
    first_name = models.CharField(
        max_length=150,
        blank=True,
        null=True,
        verbose_name=_('first name'),
    )
    last_name = models.CharField(
        max_length=150,
        verbose_name=_('last name'),
    )

    def __str__(self):
        name = self.last_name

        if self.first_name:
            name = self.first_name + " " + self.last_name
        return name

    def books(self):
        return Book.objects.filter(authors=self.id)

    def get_absolute_url(self):
        return reverse('biblioteka:authorDetail', kwargs={'pk': self.pk})

    def _get_full_name(self):
        if self.first_name:
            return self.first_name + " " + self.last_name

        return self.last_name

    full_name = property(_get_full_name)


class Publisher(models.Model):
    name = models.CharField(
        max_length=300,
        verbose_name=_('name'),
    )

    def __str__(self):
        return self.name;

    def books(self):
        return Book.objects.filter(publisher=self.id)


class Tag(models.Model):
    name = models.CharField(
        max_length=32,
        unique=True,
        verbose_name=_('name'),
    )

    def __str__(self):
        return self.name

    def books(self):
        return Book.objects.filter(tags=self.id)

    def popularity(self):
        return Book.objects.filter(tags=self.id).count()

    def get_absolute_url(self):
        return reverse('biblioteka:tagDetail', kwargs={'pk': self.pk})


class Book(models.Model):
    isbn = models.CharField(max_length=13,
                            null=True,
                            blank=True,
                            unique=True,
                            validators=[validators.RegexValidator(regex="^(978|979)([0-9]){10}$",
                                                                  message=_('This is not a valid ISBN.'))],
                            name='ISBN',
                            verbose_name=_('ISBN')
                            )

    title = models.CharField(
        max_length=500,
        verbose_name=_('title')
    )

    copies = models.PositiveSmallIntegerField(
        validators=[validators.MinValueValidator(1)],
        default=1,
        verbose_name=_('no of copies'),
    )

    authors = models.ManyToManyField(
        Author,
        blank=True,
        verbose_name=_('authors'),
    )

    tags = models.ManyToManyField(
        Tag,
        blank=True,
        verbose_name=_('tags'),
    )

    publisher = models.ForeignKey(
        Publisher,
        blank=True,
        null=True,
        verbose_name=_('publisher'),
        on_delete=models.SET_NULL,
    )

    pub_year = models.IntegerField(
        null=True,
        blank=True,
        verbose_name=_('year'),
    )

    comment = models.CharField(
        max_length=500,
        null=True,
        blank=True,
        verbose_name=_('comment')
    )

    def available_copies(self):
        return self.copies - self.rentals().filter(returned_date=None).count()

    def rentals(self):
        return Rental.objects.filter(book=self.id)

    def save(self):
        """overriding save method so that we can save Null to database, instead of empty string (project requirement)"""
        # get a list of all model fields (i.e. self._meta.fields)...
        emptystringfields = [field for field in self._meta.fields \
                             # ...that are of type CharField or Textfield...
                             if ((type(field) == models.fields.CharField) or (type(field) == models.fields.TextField)) \
                             # ...and that contain the empty string
                             and (getattr(self, field.name) == "")]
        # set each of these fields to None (which tells Django to save Null)
        for field in emptystringfields:
            setattr(self, field.name, None)
            # call the super.save() method
        super(Book, self).save()

    class Meta:
        permissions = (
            ("mark_book_read", _('Can mark a book as read.')),
            ("mark_book_unread", _('Can mark a book as unread.')),
        )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('biblioteka:bookDetail', kwargs={'pk': self.pk})


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    nickname = models.CharField(
        verbose_name=_('nickname'),
        null=True,
        blank=True,
        max_length=32,
    )

    books_read = models.ManyToManyField(
        Book,
        blank=True,
        verbose_name=_('read books'),
    )

    def mark_book_read(self, book_id):
        book = Book.objects.get(id=book_id)

        if not book:
            raise ValidationError(_("Book doesn't exist."))

        self.books_read.add(book)

    def mark_book_unread(self, book_id):
        book = Book.objects.get(id=book_id)

        if not book:
            raise ValidationError(_("Book doesn't exist."))

        self.books_read.remove(book)

    def rentals(self):
        return Rental.objects.filter(rented_by=self.user)


class Rental(models.Model):
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        verbose_name=_('rented book'),
    )

    rented_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name=_('rented by'),
    )

    rented_date = models.DateTimeField(
        verbose_name=_('rented date'),
    )

    returned_date = models.DateTimeField(
        null=True,
        blank=True,
    )

    class Meta:
        permissions = (
            ("rent_book", _('Can rent a book for themselves')),
            ("return_book", _('Can return a rented book')),
            ("rent_book_for_user", _('Can create a rental for someone else')),
            ("return_book_for_user", _('Can return a book that was borrowed by someone else')),
        )

    def __str__(self):
        return self.rented_by.__str__() + ": " + self.book.title

    def clean(self):
        if not self.pk and self.book.available_copies() < 1:
            raise ValidationError(_('No copies available.'), code='out_of_copies')

    def return_book(self, user):
        if self.rented_by != user:
            raise ValidationError(_('You can\'t return a book that was rented by someone else.'), code='wrong_user')
        self.returned_date = datetime.now()
        self.save()

biblioteka/forms.py
from django import forms
from django.db import models
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Reset, Div, HTML
from crispy_forms.bootstrap import StrictButton

from .models import Book, Author, Tag, Publisher


class BookModelForm(forms.ModelForm):
    helper = FormHelper()

    def __init__(self, *args, **kwargs):
        super(BookModelForm, self).__init__(*args, **kwargs)

        self.helper.html5_required = True

        self.helper.layout = Layout(
            'title',
            Div(
                Div(
                    'ISBN',
                    css_class='col-md-6'
                ),
                Div(
                    'copies',
                    css_class='col-md-6'
                ),
                css_class='row'
            ),
            Div(
                Div(
                    'authors',
                    'publisher',
                    css_class='col-md-6'
                ),
                Div(
                    'tags',
                    'pub_year',
                    css_class='col-md-6'
                ),
                css_class='row'
            ),
            'comment',
            StrictButton(
                '<span class="glyphicon glyphicon-save"></span> ' + _('Save'),
                css_class='btn-primary',
                type='Submit',
                value='Save'
            ),
            StrictButton(
                '<span class="glyphicon glyphicon-repeat"></span> ' + _('Reset'),
                css_class='btn-warning',
                type='Reset',
            ),
        )

    class Meta:
        model = Book
        fields = ['ISBN', 'copies', 'title', 'authors', 'tags', 'publisher', 'pub_year', 'comment']
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 4}),
        }


class AuthorModelForm(forms.ModelForm):
    helper = FormHelper()

    def __init__(self, *args, **kwargs):
        super(AuthorModelForm, self).__init__(*args, **kwargs)

        self.helper.html5_required = True

        self.helper.layout = Layout(
            Div(
                Div(
                    'first_name',
                    css_class='col-md-6'
                ),
                Div(
                    'last_name',
                    css_class='col-md-6'
                ),
                css_class='row'
            ),
            'comment',
            StrictButton('<span class="glyphicon glyphicon-save"></span> ' + _('Save'),
                css_class='btn-primary',
                type='Submit',
                value='Save'
            ),
            StrictButton(
                '<span class="glyphicon glyphicon-repeat"></span> ' + _('Reset'),
                css_class='btn-warning',
                type='Reset',
            ),
        )

    class Meta:
        model = Author
        fields = ['first_name', 'last_name']


class TagModelForm(forms.ModelForm):
    helper = FormHelper()

    def __init__(self, *args, **kwargs):
        super(TagModelForm, self).__init__(*args, **kwargs)

        self.helper.html5_required = True

        self.helper.layout = Layout(
            'name',
            StrictButton(
                '<span class="glyphicon glyphicon-save"></span> ' +_('Save'),
                css_class='btn-primary',
                type='Submit',
                value='Save'
            ),
            StrictButton(
                '<span class="glyphicon glyphicon-repeat"></span> ' + _('Reset'),
                css_class='btn-warning',
                type='Reset',
            ),
        )

    class Meta:
        model = Tag
        fields = ['name']


class PublisherModelForm(forms.ModelForm):
    helper = FormHelper()

    def __init__(self, *args, **kwargs):
        super(PublisherModelForm, self).__init__(*args, **kwargs)

        self.helper.html5_required = True

        self.helper.layout = Layout(
            'name',
            StrictButton(
                '<span class="glyphicon glyphicon-save"></span> ' +_('Save'),
                css_class='btn-primary',
                type='Submit',
                value='Save'
            ),
            StrictButton(
                '<span class="glyphicon glyphicon-repeat"></span> ' + _('Reset'),
                css_class='btn-warning',
                type='Reset',
            ),
        )

    class Meta:
        model = Publisher
        fields = ['name']


class LoginForm(AuthenticationForm):
    helper = FormHelper()

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                _("This account is inactive."),
                code='inactive',
            )

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.helper.html5_required = True
        self.helper.form_class='form-signin'
        self.helper.label_class='sr-only'

        self.fields['username'].widget.attrs={'placeholder': _('Username')}
        self.fields['password'].widget.attrs={'placeholder': _('Password')}

        self.helper.layout = Layout(
            HTML('<h2 class="form-signin-heading">' + _('Sign in') + '</h2>'),
            'username',
            'password',
            StrictButton(
                '<span class="glyphicon glyphicon-log-in"></span> ' + _('Sign in'),
                css_class='btn-primary btn-block btn-lg',
                type='Submit',
                value='Save'
            ),
        )


class TestForm(forms.Form):
    isbn = forms.RegexField(
        regex="^(978|979)([0-9]){10}$",
        label='ISBN',
        required=False,
        min_length=13,
        max_length=13,
    )

    title = forms.CharField(
        label='Tytuł',
        required=True,
        max_length=512,
    )

    helper = FormHelper()

    def __init__(self, *args, **kwargs):
        super(TestForm, self).__init__(*args, **kwargs)
        self.helper.form_method = 'POST'
        self.helper.form_action = 'biblioteka:test'
        self.helper.html5_required = True

        self.helper.layout = Layout(
            Div(
                Div(
                    'isbn',
                    css_class='col-md-6',
                ),
                Div(
                    'title',
                    css_class='col-md-6',
                ),
                css_class='row',
            ),
            Div(
                StrictButton(
                    '<span class="glyphicon glyphicon-save"></span> Zapisz',
                    css_class='btn-warning',
                    type='Submit',
                ),
                Reset('Reset', 'Resetuj', css_class='btn-warning'),
                css_class='form-group'
            )
        )

biblioteka/templates/biblioteka/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>

    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">


    <!-- Bottstrap.js -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>

    {% load staticfiles %}

    <!-- table sorter -->
    <script type="text/javascript" src="{% static 'biblioteka/jquery.tablesorter.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'biblioteka/common.js' %}"></script>

    <link rel="stylesheet" href="{% static 'biblioteka/css/style.css' %}">
</head>
<body>
{% block navbar %}{% endblock %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading lead">
            <!--<div class="row">-->
                <!--<div class="col-md-12">-->
                    <span>{% block panel_title %}{% endblock %}</span>
                <!--</div>-->
            <!--</div>-->
        </div>
        <div class="panel-body">
            <div class="buttons">
                <!--<div class="btn-group">-->
                    {% block buttons %}{% endblock %}
                <!--</div>-->
            </div>
            {% if messages %}
            <p>
                {% for message in messages %}
                    <div class="alert {% if message.tags %}{{ message.tags }}{% endif %}">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            </p>
            {% block content %}
            {% endblock %}
        </div>
        <div class="panel-footer">
            <center>
                <span class="footer-text">rzyua {% now "Y" %}</span>
            </center>
        </div>
    </div>
</div>
</body>
</html>

biblioteka/templates/biblioteka/book_confirm_delete.html
{% extends 'biblioteka/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Delete book" %}
{% endblock %}

{% block navbar %}
    {% include 'biblioteka/partial/navbar.html' with active='book' %}
{% endblock %}

{% block panel_title %}
    {% trans "Confirm delete" %}
{% endblock %}

{% block panel_title_right %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <form action="" method="post" class="form">{% csrf_token %}
            <div class="form-group">
                <label class="lead">{% trans "Are you sure you want to delete" %}
                    &nbsp<mark>{{ object }}</mark>
                    ?
                </label>
            </div>
            <div class="form-group">
                <button type="submit" value="Yes" class="btn btn-danger">
                    <span class="glyphicon glyphicon-trash"></span> {% trans "Yes" %}
                </button>
                <a href="{% url 'biblioteka:bookDetail' book.id %}" class="btn btn-default">
                    <span class="glyphicon glyphicon-remove"></span> {% trans "No" %}
                </a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

biblioteka/templates/biblioteka/book_create_form.html
{% extends 'biblioteka/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Add book" %}
{% endblock %}

{% block navbar %}
    {% include 'biblioteka/partial/navbar.html' with active='book' %}
{% endblock %}

{% block panel_title %}
    {% trans "Add book" %}
{% endblock %}

{% block panel_title_right %}{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}
    {% crispy form %}
{% endblock %}

biblioteka/templates/biblioteka/book_list.html
{% extends 'biblioteka/base.html' %}
{% load i18n %}

{% block title %}{% trans "Book list" %}{% endblock %}

{% block navbar %}
{% include 'biblioteka/partial/navbar.html' with active='book' %}
{% endblock %}

{% block panel_title %}{% trans "Books" %}{% endblock %}

{% block buttons %}
{% if perms.biblioteka.add_book %}
<a href="{% url 'biblioteka:bookCreate' %}" class="btn btn-primary">
    <span class="glyphicon glyphicon-plus"></span> {% trans "Add book" %}
</a>
{% endif %}
{% endblock %}

{% block content %}
{% include 'biblioteka/partial/book_table.html' with book_list=book_list action_buttons=False %}
{% endblock %}

biblioteka/templates/biblioteka/index.html
{{ book }}

biblioteka/templates/biblioteka/publisher_confirm_delete.html
{% extends 'biblioteka/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Delete publisher" %}
{% endblock %}

{% block navbar %}
    {% include 'biblioteka/partial/navbar.html' with active='publisher' %}
{% endblock %}

{% block panel_title %}
    {% trans "Confirm delete" %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <form action="" method="post" class="form">{% csrf_token %}
            <div class="form-group">
                <label class="lead">{% trans "Are you sure you want to delete" %}
                    &nbsp;<mark>{{ object }}</mark>
                    ?
                </label>
            </div>
            <div class="form-group">
                <button type="submit" value="Yes" class="btn btn-danger">{% trans "Yes" %}</button>
                <a href="{% url 'biblioteka:publisherDetail' publisher.id %}" class="btn btn-default">{% trans "No" %}</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

biblioteka/templates/biblioteka/publisher_create_form.html
{% extends 'biblioteka/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Add publisher" %}
{% endblock %}

{% block navbar %}
    {% include 'biblioteka/partial/navbar.html' with active='publisher' %}
{% endblock %}

{% block panel_title %}
    {% trans "Add publisher" %}
{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}
    {% crispy form %}
{% endblock %}

biblioteka/templates/biblioteka/publisher_detail.html
{% extends 'biblioteka/base.html' %}
{% load i18n %}

{% block title %}
    {{ publisher }}
{% endblock %}

{% block navbar %}
    {% include 'biblioteka/partial/navbar.html' with active='publisher' %}
{% endblock %}

{% block panel_title %}
    {{ publisher }}
{% endblock %}

{% block buttons %}
    {% if perms.biblioteka.delete_publisher %}
        <a href="{% url 'biblioteka:publisherDelete' publisher.id %}" class="btn btn-danger">
            <span class="glyphicon glyphicon-trash"></span> {% trans "Delete" %}
        </a>
    {% endif %}
    {% if perms.biblioteka.change_publisher %}
        <a href="{% url 'biblioteka:publisherUpdate' publisher.id %}" class="btn btn-primary">
            <span class="glyphicon glyphicon-edit"></span> {% trans "Edit" %}
        </a>
    {% endif %}
{% endblock %}

{% block content %}
    <h4>{% trans "Books by this publisher" %}</h4>
    {% include 'biblioteka/partial/book_table.html' with book_list=publisher.books %}
{% endblock %}

biblioteka/templates/biblioteka/tag_confirm_delete.html
{% extends 'biblioteka/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Delete tag" %}
{% endblock %}

{% block navbar %}
    {% include 'biblioteka/partial/navbar.html' with active='tag' %}
{% endblock %}

{% block panel_title %}
    {% trans "Confirm delete" %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <form action="" method="post" class="form">{% csrf_token %}
            <div class="form-group">
                <label class="lead">{% trans "Are you sure you want to delete" %}
                    &nbsp<mark>{{ object }}</mark>
                    ?
                </label>
            </div>
            <div class="form-group">
                <button type="submit" value="Yes" class="btn btn-danger">{% trans "Yes" %}</button>
                <a href="{% url 'biblioteka:tagDetail' tag.id %}" class="btn btn-default">{% trans "No" %}</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

biblioteka/templates/biblioteka/tag_create_form.html
{% extends 'biblioteka/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Add tag" %}
{% endblock %}

{% block navbar %}
    {% include 'biblioteka/partial/navbar.html' with active='tag' %}
{% endblock %}

{% block panel_title %}
    {% trans "Add tag" %}
{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}
    {% crispy form %}
{% endblock %}

biblioteka/templates/biblioteka/tag_detail.html
{% extends 'biblioteka/base.html' %}
{% load i18n %}

{% block title %}
    {{ tag }}
{% endblock %}

{% block navbar %}
    {% include 'biblioteka/partial/navbar.html' with active='tag' %}
{% endblock %}

{% block panel_title %}
    {{ tag }}
{% endblock %}

{% block buttons %}
    {% if perms.biblioteka.delete_tag %}
        <a href="{% url 'biblioteka:tagDelete' tag.id %}" class="btn btn-danger">
            <span class="glyphicon glyphicon-trash"></span> {% trans "Delete" %}
        </a>
    {% endif %}
    {% if perms.biblioteka.change_tag %}
        <a href="{% url 'biblioteka:tagUpdate' tag.id %}" class="btn btn-primary">
            <span class="glyphicon glyphicon-edit"></span> {% trans "Edit" %}
        </a>
    {% endif %}
{% endblock %}

{% block content %}
<h4>{% trans "Books with this tag" %}</h4>
    {% include 'biblioteka/partial/book_table.html' with book_list=tag.books action_buttons=False %}
{% endblock %}

biblioteka/templates/biblioteka/tag_list.html
{% extends 'biblioteka/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Tag list" %}
{% endblock %}

{% block navbar %}
    {% include 'biblioteka/partial/navbar.html' with active='tag' %}
{% endblock %}

{% block panel_title %}
    {% trans "Tags" %}
{% endblock %}

{% block buttons %}
    {% if perms.biblioteka.add_tag %}
        <a href="{% url 'biblioteka:tagCreate' %}" class="btn btn-primary">
            <span class="glyphicon glyphicon-plus"></span> {% trans "Add tag" %}
        </a>
    {% endif %}
{% endblock %}

{% block content %}
    {% include 'biblioteka/partial/tag_table.html' with tag_list=tag_list action_buttons=False %}
{% endblock %}

biblioteka/templates/biblioteka/tag_update_form.html
{% extends 'biblioteka/base.html' %}
{% load i18n %}

{% block title %}
    {% trans "Edit tag" %}
{% endblock %}

{% block navbar %}
    {% include 'biblioteka/partial/navbar.html' with active='tag' %}
{% endblock %}

{% block panel_title %}
    {% trans "Edit tag" %}
{% endblock %}

{% block panel_title_right %}
{% endblock %}

{% block content %}
    {% load crispy_forms_tags %}
    {% crispy form %}
{% endblock %}

biblioteka/templates/biblioteka/test.html
{% extends 'biblioteka/base.html' %}

{% block title %}Test{% endblock %}

{% block navbar %}
{% include 'biblioteka/partial/navbar.html' with active='test' %}
{% endblock %}

{% block panel_title %}Test{% endblock %}

{% block panel_title_right %}
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
{% crispy form %}
{% endblock %}

{% include 'biblioteka/partial/foot.html' %}